### PR TITLE
Nuke patch for cryptsetup 2.0.4

### PR DESCRIPTION
**Pull request by maicardi**
Nuke patch for cryptsetup 2.0.4 as in Ubuntu 18.10

### CODE REVIEW

**Comment by roema** [comment]
Thank for the pull-request!

I have seen, that creating the .deb files generates some warnings/errors about the version/maintainer's in debian/changelog file.

I have changed some lines in changelog, please take a look

changelog

I am not sure if this is correct...??

**Comment by maicardi** [comment]
Hi roema and thanks for your work!

Yes, you're absolutely right... I have built the deb files before modifying the changelog file! Thanks for pointing it out.

I've modified cryptsetup-2.0.4.patch to reflect your suggestions, now it builds without warnings.

**Comment by roema** [comment]
Thank you, maicardi!!
I am considering whether it makes sense to delete the keys after a certain number of attempts? What do you think?

**Comment by maicardi** [comment]
I would keep it disabled by default, because I think it's EXTREMELY dangerous.
You should always keep an updated backup of your headers, otherwise whoever should try to access your PC (say your wife to see if your cheating on her of your kids just to play) would DESTROY your data.
If you are, instead, thinking about NSA or any other forensic institutions, they would do a full backup of the HDDs before trying to access.

**Comment by roema** [comment]
yes you are right, I agree with you!

**Pull request merged**
